services:
  # Tüm servislerin paylaştığı TEK RabbitMQ broker'ı.
  # project buraya publish eder; notificationservice ve statement buradan dinler.
  rabbitmq:
    image: rabbitmq:3-management
    container_name: digiwallet-rabbitmq
    ports:
      - "5672:5672"    # uygulama bağlantısı (AMQP)
      - "15672:15672"  # yönetim arayüzü -> http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # project servisinin veritabanı
  postgres-wallet:
    image: postgres:16
    container_name: digiwallet-postgres-wallet
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  # statement servisinin veritabanı
  postgres-statement:
    image: postgres:16
    container_name: digiwallet-postgres-statement
    environment:
      POSTGRES_DB: statement
      POSTGRES_USER: statement_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"

  postgres-transfer:
    image: postgres:16
    container_name: digiwallet-postgres-transfer
    environment:
      POSTGRES_DB: transfers
      POSTGRES_USER: transfer_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
      
