services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # uygulama bağlantısı
      - "15672:15672"  # yönetim arayüzü
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
