spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/statement
    username: statement_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: statement
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
