spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: project
