package com.digiwallet.service.transfer.constants;

public enum EventType {
    ACCOUNT_OPENED,
    MONEY_DEPOSITED,
    MONEY_WITHDRAWN,
    TRANSFER_WITHDRAW_REQUESTED,
    TRANSFER_DEPOSIT_REQUESTED,
    TRANSFER_WITHDRAW_COMPLETED,
    TRANSFER_WITHDRAW_FAILED,
    TRANSFER_DEPOSIT_COMPLETED,
    TRANSFER_COMPENSATE_REQUESTED
}

