spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: project
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
